name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Check Storybook static folder
        run: ls -la storybook-static

      - name: Start Storybook and run visual tests with Loki
        run: npx start-server-and-test 'npm run storybook -- --port 6006 --host 0.0.0.0' http://0.0.0.0:6006 'npm run test:ui:ci'
        env:
          REACT_URI: http://0.0.0.0:6006
