name: linting, testing, building
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.9.0]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Linting TypeScript
        run: npm run lint:ts
        if: always()
      - name: Linting SCSS
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      - name: Build Storybook
        run: npm run storybook:build
        if: always()
      - name: Check if Storybook build is successful
        run: ls -alh ./storybook-static
      - name: Wait for Storybook build to be available
        run: sleep 60
      - name: Update reference screenshots
        run: npx loki update --reactUri="file:./storybook-static"
      - name: Debug Loki Logs
        run: npx loki test --verbose
      - name: Screenshot testing
        run: npm run test:ui:ci
        if: always()
      - name: Update reference screenshots if tests fail
        if: failure()
        run: npx loki update --reactUri="file:./storybook-static"
