name: linting, testing, building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # Using a more recent version
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build production project
        run: npm run build:prod

      - name: Linting TypeScript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      - name: Run unit tests
        run: npm run test:unit

      - name: Build Storybook
        run: npm run storybook:build

      - name: Check Storybook static folder
        run: ls -la storybook-static

      - name: Start Storybook in the background
        run: |
          npm run storybook --port 48899 --host 0.0.0.0 & # Start Storybook in the background
          sleep 5 # Give time for Storybook to start

      - name: Run visual tests with Loki
        run: npm run test:ui:ci
# name: linting, testing, building
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# jobs:
#   pipeline:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [22.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install modules
#         run: npm install
#       - name: build production project
#         run: npm run build:prod
#       - name: linting typescript
#         run: npm run lint:ts
#       - name: linting css
#         run: npm run lint:scss
#       - name: unit testing
#         run: npm run test:unit
#       - name: build storybook
#         run: npm run storybook:build
#       - name: Check Storybook static folder
#         run: ls -la storybook-static
#       - name: screenshot testing
#         run: npm run test:ui:ci
